### ISSUE TITLE
zaproxy 1.0.0-rc.1 is now available

### ISSUE THREAD

**Issue by binarymist** [ZFPSystems/zaproxy-automation#1]
There is a [new release](https://www.npmjs.com/package/zaproxy/v/1.0.0-rc.1) of zaproxy available with some [breaking changes](https://github.com/zaproxy/zap-api-nodejs/blob/master/CHANGELOG.md). I'd love to know how you get on with it? Let me know if you need any assistance with upgrading.

**Comment by pzaino** [comment]
Hi @binarymist will start testing zaproxy 1.0.1 soon, generally I avoid RCs updates on here because I really have very little time available to test and fix issues, since now release 1.0.1 is out will test that one soon, thx

**Comment by pzaino** [comment]
Updated documentation and tested with latest zaproxy release 2.12.
